// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Tracing implementation internals
#include "verilated_fst_c.h"
#include "Vtop__Syms.h"


VL_ATTR_COLD void Vtop___024root__trace_init_sub__TOP__0(Vtop___024root* vlSelf, VerilatedFst* tracep) {
    if (false && vlSelf) {}  // Prevent unused
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_init_sub__TOP__0\n"); );
    // Init
    const int c = vlSymsp->__Vm_baseCode;
    // Body
    tracep->declBit(c+193,"clk_i",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+194,"A",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBus(c+195,"B",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBus(c+196,"opcode",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 1,0);
    tracep->declBus(c+197,"O",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->pushNamePrefix("top ");
    tracep->declBit(c+193,"clk_i",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+194,"A",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBus(c+195,"B",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBus(c+196,"opcode",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 1,0);
    tracep->declBus(c+197,"O",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->pushNamePrefix("dut ");
    tracep->declBit(c+193,"clk_i",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+194,"A",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBus(c+195,"B",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBus(c+196,"opcode",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 1,0);
    tracep->declBus(c+197,"O",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBus(c+198,"a_exponent",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 7,0);
    tracep->declBus(c+199,"a_mantissa",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 23,0);
    tracep->declBus(c+200,"b_exponent",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 7,0);
    tracep->declBus(c+201,"b_mantissa",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 23,0);
    tracep->declBit(c+188,"o_sign",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBus(c+189,"o_exponent",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 7,0);
    tracep->declBus(c+190,"o_mantissa",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 24,0);
    tracep->declBus(c+191,"adder_a_in",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 31,0);
    tracep->declBus(c+192,"adder_b_in",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 31,0);
    tracep->declBus(c+21,"adder_out",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 31,0);
    tracep->declBus(c+208,"multiplier_a_in",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 31,0);
    tracep->declBus(c+209,"multiplier_b_in",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 31,0);
    tracep->declBus(c+6,"multiplier_out",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 31,0);
    tracep->declBus(c+210,"divider_a_in",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 31,0);
    tracep->declBus(c+211,"divider_b_in",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 31,0);
    tracep->declBus(c+202,"divider_out",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 31,0);
    tracep->declBit(c+203,"a_sign",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+204,"b_sign",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+212,"ADD",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+213,"SUB",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+212,"DIV",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+213,"MUL",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->pushNamePrefix("A1 ");
    tracep->declBus(c+191,"a",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBus(c+192,"b",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBus(c+21,"out",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBit(c+22,"a_sign",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBus(c+23,"a_exponent",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 7,0);
    tracep->declBus(c+24,"a_mantissa",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 23,0);
    tracep->declBit(c+25,"b_sign",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBus(c+26,"b_exponent",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 7,0);
    tracep->declBus(c+27,"b_mantissa",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 23,0);
    tracep->declBit(c+28,"o_sign",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBus(c+29,"o_exponent",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 7,0);
    tracep->declBus(c+30,"o_mantissa",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 24,0);
    tracep->declBus(c+31,"diff",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 7,0);
    tracep->declBus(c+32,"tmp_mantissa",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 23,0);
    tracep->declBus(c+214,"tmp_exponent",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 7,0);
    tracep->declBus(c+33,"i_e",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 7,0);
    tracep->declBus(c+34,"i_m",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 24,0);
    tracep->declBus(c+35,"o_e",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 7,0);
    tracep->declBus(c+36,"o_m",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 24,0);
    tracep->pushNamePrefix("norm1 ");
    tracep->declBus(c+33,"in_e",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 7,0);
    tracep->declBus(c+34,"in_m",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 24,0);
    tracep->declBus(c+35,"out_e",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 7,0);
    tracep->declBus(c+36,"out_m",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 24,0);
    tracep->popNamePrefix(2);
    tracep->pushNamePrefix("D1 ");
    tracep->declBus(c+210,"a",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBus(c+211,"b",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBus(c+202,"out",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBus(c+156,"b_reciprocal",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 31,0);
    tracep->pushNamePrefix("mult ");
    tracep->declBus(c+210,"a",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBus(c+156,"b",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBus(c+202,"out",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBit(c+157,"a_sign",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBus(c+174,"a_exponent",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 7,0);
    tracep->declBus(c+175,"a_mantissa",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 23,0);
    tracep->declBit(c+158,"b_sign",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBus(c+176,"b_exponent",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 7,0);
    tracep->declBus(c+177,"b_mantissa",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 23,0);
    tracep->declBit(c+159,"o_sign",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBus(c+178,"o_exponent",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 7,0);
    tracep->declBus(c+179,"o_mantissa",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 24,0);
    tracep->declQuad(c+180,"product",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 47,0);
    tracep->declBus(c+182,"i_e",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 7,0);
    tracep->declQuad(c+183,"i_m",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 47,0);
    tracep->declBus(c+185,"o_e",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 7,0);
    tracep->declQuad(c+186,"o_m",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 47,0);
    tracep->pushNamePrefix("norm1 ");
    tracep->declBus(c+182,"in_e",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 7,0);
    tracep->declQuad(c+183,"in_m",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 47,0);
    tracep->declBus(c+185,"out_e",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 7,0);
    tracep->declQuad(c+186,"out_m",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 47,0);
    tracep->popNamePrefix(2);
    tracep->pushNamePrefix("recip ");
    tracep->declBus(c+211,"in",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBus(c+156,"out",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBus(c+215,"D",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 31,0);
    tracep->declBus(c+216,"C1",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 31,0);
    tracep->declBus(c+217,"C2",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 31,0);
    tracep->declBus(c+218,"C3",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 31,0);
    tracep->declBus(c+51,"N0",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 31,0);
    tracep->declBus(c+104,"N1",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 31,0);
    tracep->declBus(c+205,"N2",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 31,0);
    tracep->declBus(c+37,"S0_2D_out",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 31,0);
    tracep->declBus(c+206,"S1_DN0_out",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 31,0);
    tracep->declBus(c+85,"S1_2min_DN0_out",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 31,0);
    tracep->declBus(c+207,"S2_DN1_out",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 31,0);
    tracep->declBus(c+137,"S2_2minDN1_out",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 31,0);
    tracep->declBus(c+38,"S0_N0_in",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 31,0);
    tracep->pushNamePrefix("S0_2D ");
    tracep->declBus(c+217,"a",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBus(c+215,"b",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBus(c+37,"out",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBit(c+212,"a_sign",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBus(c+219,"a_exponent",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 7,0);
    tracep->declBus(c+220,"a_mantissa",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 23,0);
    tracep->declBit(c+1,"b_sign",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBus(c+39,"b_exponent",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 7,0);
    tracep->declBus(c+40,"b_mantissa",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 23,0);
    tracep->declBit(c+2,"o_sign",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBus(c+41,"o_exponent",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 7,0);
    tracep->declBus(c+42,"o_mantissa",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 24,0);
    tracep->declQuad(c+43,"product",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 47,0);
    tracep->declBus(c+45,"i_e",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 7,0);
    tracep->declQuad(c+46,"i_m",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 47,0);
    tracep->declBus(c+48,"o_e",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 7,0);
    tracep->declQuad(c+49,"o_m",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 47,0);
    tracep->pushNamePrefix("norm1 ");
    tracep->declBus(c+45,"in_e",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 7,0);
    tracep->declQuad(c+46,"in_m",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 47,0);
    tracep->declBus(c+48,"out_e",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 7,0);
    tracep->declQuad(c+49,"out_m",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 47,0);
    tracep->popNamePrefix(2);
    tracep->pushNamePrefix("S0_N0 ");
    tracep->declBus(c+216,"a",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBus(c+38,"b",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBus(c+51,"out",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBit(c+52,"a_sign",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBus(c+53,"a_exponent",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 7,0);
    tracep->declBus(c+54,"a_mantissa",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 23,0);
    tracep->declBit(c+55,"b_sign",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBus(c+56,"b_exponent",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 7,0);
    tracep->declBus(c+57,"b_mantissa",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 23,0);
    tracep->declBit(c+58,"o_sign",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBus(c+59,"o_exponent",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 7,0);
    tracep->declBus(c+60,"o_mantissa",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 24,0);
    tracep->declBus(c+61,"diff",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 7,0);
    tracep->declBus(c+62,"tmp_mantissa",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 23,0);
    tracep->declBus(c+221,"tmp_exponent",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 7,0);
    tracep->declBus(c+63,"i_e",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 7,0);
    tracep->declBus(c+64,"i_m",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 24,0);
    tracep->declBus(c+65,"o_e",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 7,0);
    tracep->declBus(c+66,"o_m",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 24,0);
    tracep->pushNamePrefix("norm1 ");
    tracep->declBus(c+63,"in_e",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 7,0);
    tracep->declBus(c+64,"in_m",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 24,0);
    tracep->declBus(c+65,"out_e",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 7,0);
    tracep->declBus(c+66,"out_m",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 24,0);
    tracep->popNamePrefix(2);
    tracep->pushNamePrefix("S1_2minDN0 ");
    tracep->declBus(c+218,"a",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBus(c+70,"b",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBus(c+85,"out",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBit(c+86,"a_sign",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBus(c+87,"a_exponent",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 7,0);
    tracep->declBus(c+88,"a_mantissa",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 23,0);
    tracep->declBit(c+89,"b_sign",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBus(c+90,"b_exponent",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 7,0);
    tracep->declBus(c+91,"b_mantissa",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 23,0);
    tracep->declBit(c+92,"o_sign",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBus(c+93,"o_exponent",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 7,0);
    tracep->declBus(c+94,"o_mantissa",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 24,0);
    tracep->declBus(c+95,"diff",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 7,0);
    tracep->declBus(c+96,"tmp_mantissa",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 23,0);
    tracep->declBus(c+222,"tmp_exponent",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 7,0);
    tracep->declBus(c+97,"i_e",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 7,0);
    tracep->declBus(c+98,"i_m",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 24,0);
    tracep->declBus(c+99,"o_e",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 7,0);
    tracep->declBus(c+100,"o_m",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 24,0);
    tracep->pushNamePrefix("norm1 ");
    tracep->declBus(c+97,"in_e",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 7,0);
    tracep->declBus(c+98,"in_m",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 24,0);
    tracep->declBus(c+99,"out_e",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 7,0);
    tracep->declBus(c+100,"out_m",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 24,0);
    tracep->popNamePrefix(2);
    tracep->pushNamePrefix("S1_DN0 ");
    tracep->declBus(c+215,"a",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBus(c+51,"b",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBus(c+206,"out",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBit(c+67,"a_sign",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBus(c+71,"a_exponent",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 7,0);
    tracep->declBus(c+72,"a_mantissa",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 23,0);
    tracep->declBit(c+68,"b_sign",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBus(c+73,"b_exponent",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 7,0);
    tracep->declBus(c+74,"b_mantissa",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 23,0);
    tracep->declBit(c+69,"o_sign",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBus(c+75,"o_exponent",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 7,0);
    tracep->declBus(c+76,"o_mantissa",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 24,0);
    tracep->declQuad(c+77,"product",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 47,0);
    tracep->declBus(c+79,"i_e",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 7,0);
    tracep->declQuad(c+80,"i_m",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 47,0);
    tracep->declBus(c+82,"o_e",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 7,0);
    tracep->declQuad(c+83,"o_m",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 47,0);
    tracep->pushNamePrefix("norm1 ");
    tracep->declBus(c+79,"in_e",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 7,0);
    tracep->declQuad(c+80,"in_m",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 47,0);
    tracep->declBus(c+82,"out_e",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 7,0);
    tracep->declQuad(c+83,"out_m",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 47,0);
    tracep->popNamePrefix(2);
    tracep->pushNamePrefix("S1_N1 ");
    tracep->declBus(c+51,"a",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBus(c+85,"b",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBus(c+104,"out",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBit(c+101,"a_sign",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBus(c+105,"a_exponent",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 7,0);
    tracep->declBus(c+106,"a_mantissa",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 23,0);
    tracep->declBit(c+102,"b_sign",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBus(c+107,"b_exponent",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 7,0);
    tracep->declBus(c+108,"b_mantissa",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 23,0);
    tracep->declBit(c+103,"o_sign",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBus(c+109,"o_exponent",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 7,0);
    tracep->declBus(c+110,"o_mantissa",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 24,0);
    tracep->declQuad(c+111,"product",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 47,0);
    tracep->declBus(c+113,"i_e",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 7,0);
    tracep->declQuad(c+114,"i_m",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 47,0);
    tracep->declBus(c+116,"o_e",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 7,0);
    tracep->declQuad(c+117,"o_m",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 47,0);
    tracep->pushNamePrefix("norm1 ");
    tracep->declBus(c+113,"in_e",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 7,0);
    tracep->declQuad(c+114,"in_m",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 47,0);
    tracep->declBus(c+116,"out_e",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 7,0);
    tracep->declQuad(c+117,"out_m",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 47,0);
    tracep->popNamePrefix(2);
    tracep->pushNamePrefix("S2_2minDN1 ");
    tracep->declBus(c+218,"a",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBus(c+122,"b",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBus(c+137,"out",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBit(c+138,"a_sign",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBus(c+139,"a_exponent",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 7,0);
    tracep->declBus(c+140,"a_mantissa",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 23,0);
    tracep->declBit(c+141,"b_sign",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBus(c+142,"b_exponent",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 7,0);
    tracep->declBus(c+143,"b_mantissa",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 23,0);
    tracep->declBit(c+144,"o_sign",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBus(c+145,"o_exponent",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 7,0);
    tracep->declBus(c+146,"o_mantissa",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 24,0);
    tracep->declBus(c+147,"diff",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 7,0);
    tracep->declBus(c+148,"tmp_mantissa",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 23,0);
    tracep->declBus(c+223,"tmp_exponent",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 7,0);
    tracep->declBus(c+149,"i_e",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 7,0);
    tracep->declBus(c+150,"i_m",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 24,0);
    tracep->declBus(c+151,"o_e",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 7,0);
    tracep->declBus(c+152,"o_m",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 24,0);
    tracep->pushNamePrefix("norm1 ");
    tracep->declBus(c+149,"in_e",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 7,0);
    tracep->declBus(c+150,"in_m",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 24,0);
    tracep->declBus(c+151,"out_e",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 7,0);
    tracep->declBus(c+152,"out_m",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 24,0);
    tracep->popNamePrefix(2);
    tracep->pushNamePrefix("S2_DN1 ");
    tracep->declBus(c+215,"a",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBus(c+104,"b",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBus(c+207,"out",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBit(c+119,"a_sign",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBus(c+123,"a_exponent",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 7,0);
    tracep->declBus(c+124,"a_mantissa",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 23,0);
    tracep->declBit(c+120,"b_sign",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBus(c+125,"b_exponent",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 7,0);
    tracep->declBus(c+126,"b_mantissa",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 23,0);
    tracep->declBit(c+121,"o_sign",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBus(c+127,"o_exponent",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 7,0);
    tracep->declBus(c+128,"o_mantissa",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 24,0);
    tracep->declQuad(c+129,"product",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 47,0);
    tracep->declBus(c+131,"i_e",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 7,0);
    tracep->declQuad(c+132,"i_m",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 47,0);
    tracep->declBus(c+134,"o_e",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 7,0);
    tracep->declQuad(c+135,"o_m",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 47,0);
    tracep->pushNamePrefix("norm1 ");
    tracep->declBus(c+131,"in_e",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 7,0);
    tracep->declQuad(c+132,"in_m",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 47,0);
    tracep->declBus(c+134,"out_e",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 7,0);
    tracep->declQuad(c+135,"out_m",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 47,0);
    tracep->popNamePrefix(2);
    tracep->pushNamePrefix("S2_N2 ");
    tracep->declBus(c+104,"a",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBus(c+137,"b",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBus(c+205,"out",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBit(c+153,"a_sign",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBus(c+160,"a_exponent",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 7,0);
    tracep->declBus(c+161,"a_mantissa",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 23,0);
    tracep->declBit(c+154,"b_sign",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBus(c+162,"b_exponent",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 7,0);
    tracep->declBus(c+163,"b_mantissa",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 23,0);
    tracep->declBit(c+155,"o_sign",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBus(c+164,"o_exponent",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 7,0);
    tracep->declBus(c+165,"o_mantissa",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 24,0);
    tracep->declQuad(c+166,"product",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 47,0);
    tracep->declBus(c+168,"i_e",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 7,0);
    tracep->declQuad(c+169,"i_m",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 47,0);
    tracep->declBus(c+171,"o_e",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 7,0);
    tracep->declQuad(c+172,"o_m",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 47,0);
    tracep->pushNamePrefix("norm1 ");
    tracep->declBus(c+168,"in_e",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 7,0);
    tracep->declQuad(c+169,"in_m",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 47,0);
    tracep->declBus(c+171,"out_e",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 7,0);
    tracep->declQuad(c+172,"out_m",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 47,0);
    tracep->popNamePrefix(4);
    tracep->pushNamePrefix("M1 ");
    tracep->declBus(c+208,"a",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBus(c+209,"b",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBus(c+6,"out",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBit(c+3,"a_sign",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBus(c+7,"a_exponent",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 7,0);
    tracep->declBus(c+8,"a_mantissa",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 23,0);
    tracep->declBit(c+4,"b_sign",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBus(c+9,"b_exponent",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 7,0);
    tracep->declBus(c+10,"b_mantissa",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 23,0);
    tracep->declBit(c+5,"o_sign",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBus(c+11,"o_exponent",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 7,0);
    tracep->declBus(c+12,"o_mantissa",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 24,0);
    tracep->declQuad(c+13,"product",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 47,0);
    tracep->declBus(c+15,"i_e",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 7,0);
    tracep->declQuad(c+16,"i_m",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 47,0);
    tracep->declBus(c+18,"o_e",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 7,0);
    tracep->declQuad(c+19,"o_m",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 47,0);
    tracep->pushNamePrefix("norm1 ");
    tracep->declBus(c+15,"in_e",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 7,0);
    tracep->declQuad(c+16,"in_m",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 47,0);
    tracep->declBus(c+18,"out_e",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 7,0);
    tracep->declQuad(c+19,"out_m",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 47,0);
    tracep->popNamePrefix(4);
}

VL_ATTR_COLD void Vtop___024root__trace_init_top(Vtop___024root* vlSelf, VerilatedFst* tracep) {
    if (false && vlSelf) {}  // Prevent unused
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_init_top\n"); );
    // Body
    Vtop___024root__trace_init_sub__TOP__0(vlSelf, tracep);
}

VL_ATTR_COLD void Vtop___024root__trace_full_top_0(void* voidSelf, VerilatedFst::Buffer* bufp);
void Vtop___024root__trace_chg_top_0(void* voidSelf, VerilatedFst::Buffer* bufp);
void Vtop___024root__trace_cleanup(void* voidSelf, VerilatedFst* /*unused*/);

VL_ATTR_COLD void Vtop___024root__trace_register(Vtop___024root* vlSelf, VerilatedFst* tracep) {
    if (false && vlSelf) {}  // Prevent unused
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_register\n"); );
    // Body
    tracep->addFullCb(&Vtop___024root__trace_full_top_0, vlSelf);
    tracep->addChgCb(&Vtop___024root__trace_chg_top_0, vlSelf);
    tracep->addCleanupCb(&Vtop___024root__trace_cleanup, vlSelf);
}

VL_ATTR_COLD void Vtop___024root__trace_full_sub_0(Vtop___024root* vlSelf, VerilatedFst::Buffer* bufp);

VL_ATTR_COLD void Vtop___024root__trace_full_top_0(void* voidSelf, VerilatedFst::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_full_top_0\n"); );
    // Init
    Vtop___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vtop___024root*>(voidSelf);
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    // Body
    Vtop___024root__trace_full_sub_0((&vlSymsp->TOP), bufp);
}

VL_ATTR_COLD void Vtop___024root__trace_full_sub_0(Vtop___024root* vlSelf, VerilatedFst::Buffer* bufp) {
    if (false && vlSelf) {}  // Prevent unused
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_full_sub_0\n"); );
    // Init
    uint32_t* const oldp VL_ATTR_UNUSED = bufp->oldp(vlSymsp->__Vm_baseCode);
    // Body
    bufp->fullBit(oldp+1,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S0_2D__DOT__b_sign));
    bufp->fullBit(oldp+2,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S0_2D__DOT__o_sign));
    bufp->fullBit(oldp+3,(vlSelf->top__DOT__dut__DOT__M1__DOT__a_sign));
    bufp->fullBit(oldp+4,(vlSelf->top__DOT__dut__DOT__M1__DOT__b_sign));
    bufp->fullBit(oldp+5,(vlSelf->top__DOT__dut__DOT__M1__DOT__o_sign));
    bufp->fullIData(oldp+6,((((IData)(vlSelf->top__DOT__dut__DOT__M1__DOT__o_sign) 
                              << 0x1fU) | (((IData)(vlSelf->top__DOT__dut__DOT__M1__DOT__o_exponent) 
                                            << 0x17U) 
                                           | (0x7fffffU 
                                              & vlSelf->top__DOT__dut__DOT__M1__DOT__o_mantissa)))),32);
    bufp->fullCData(oldp+7,(vlSelf->top__DOT__dut__DOT__M1__DOT__a_exponent),8);
    bufp->fullIData(oldp+8,(vlSelf->top__DOT__dut__DOT__M1__DOT__a_mantissa),24);
    bufp->fullCData(oldp+9,(vlSelf->top__DOT__dut__DOT__M1__DOT__b_exponent),8);
    bufp->fullIData(oldp+10,(vlSelf->top__DOT__dut__DOT__M1__DOT__b_mantissa),24);
    bufp->fullCData(oldp+11,(vlSelf->top__DOT__dut__DOT__M1__DOT__o_exponent),8);
    bufp->fullIData(oldp+12,(vlSelf->top__DOT__dut__DOT__M1__DOT__o_mantissa),25);
    bufp->fullQData(oldp+13,(vlSelf->top__DOT__dut__DOT__M1__DOT__product),48);
    bufp->fullCData(oldp+15,(vlSelf->top__DOT__dut__DOT__M1__DOT__i_e),8);
    bufp->fullQData(oldp+16,(vlSelf->top__DOT__dut__DOT__M1__DOT__i_m),48);
    bufp->fullCData(oldp+18,(vlSelf->top__DOT__dut__DOT__M1__DOT__o_e),8);
    bufp->fullQData(oldp+19,(vlSelf->top__DOT__dut__DOT__M1__DOT__o_m),48);
    bufp->fullIData(oldp+21,(vlSelf->top__DOT__dut__DOT__adder_out),32);
    bufp->fullBit(oldp+22,(vlSelf->top__DOT__dut__DOT__A1__DOT__a_sign));
    bufp->fullCData(oldp+23,(vlSelf->top__DOT__dut__DOT__A1__DOT__a_exponent),8);
    bufp->fullIData(oldp+24,(vlSelf->top__DOT__dut__DOT__A1__DOT__a_mantissa),24);
    bufp->fullBit(oldp+25,(vlSelf->top__DOT__dut__DOT__A1__DOT__b_sign));
    bufp->fullCData(oldp+26,(vlSelf->top__DOT__dut__DOT__A1__DOT__b_exponent),8);
    bufp->fullIData(oldp+27,(vlSelf->top__DOT__dut__DOT__A1__DOT__b_mantissa),24);
    bufp->fullBit(oldp+28,(vlSelf->top__DOT__dut__DOT__A1__DOT__o_sign));
    bufp->fullCData(oldp+29,(vlSelf->top__DOT__dut__DOT__A1__DOT__o_exponent),8);
    bufp->fullIData(oldp+30,(vlSelf->top__DOT__dut__DOT__A1__DOT__o_mantissa),25);
    bufp->fullCData(oldp+31,(vlSelf->top__DOT__dut__DOT__A1__DOT__diff),8);
    bufp->fullIData(oldp+32,(vlSelf->top__DOT__dut__DOT__A1__DOT__tmp_mantissa),24);
    bufp->fullCData(oldp+33,(vlSelf->top__DOT__dut__DOT__A1__DOT__i_e),8);
    bufp->fullIData(oldp+34,(vlSelf->top__DOT__dut__DOT__A1__DOT__i_m),25);
    bufp->fullCData(oldp+35,(vlSelf->top__DOT__dut__DOT__A1__DOT__o_e),8);
    bufp->fullIData(oldp+36,(vlSelf->top__DOT__dut__DOT__A1__DOT__o_m),25);
    bufp->fullIData(oldp+37,((((IData)(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S0_2D__DOT__o_sign) 
                               << 0x1fU) | (((IData)(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S0_2D__DOT__o_exponent) 
                                             << 0x17U) 
                                            | (0x7fffffU 
                                               & vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S0_2D__DOT__o_mantissa)))),32);
    bufp->fullIData(oldp+38,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S0_N0_in),32);
    bufp->fullCData(oldp+39,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S0_2D__DOT__b_exponent),8);
    bufp->fullIData(oldp+40,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S0_2D__DOT__b_mantissa),24);
    bufp->fullCData(oldp+41,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S0_2D__DOT__o_exponent),8);
    bufp->fullIData(oldp+42,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S0_2D__DOT__o_mantissa),25);
    bufp->fullQData(oldp+43,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S0_2D__DOT__product),48);
    bufp->fullCData(oldp+45,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S0_2D__DOT__i_e),8);
    bufp->fullQData(oldp+46,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S0_2D__DOT__i_m),48);
    bufp->fullCData(oldp+48,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S0_2D__DOT__o_e),8);
    bufp->fullQData(oldp+49,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S0_2D__DOT__o_m),48);
    bufp->fullIData(oldp+51,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__N0),32);
    bufp->fullBit(oldp+52,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S0_N0__DOT__a_sign));
    bufp->fullCData(oldp+53,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S0_N0__DOT__a_exponent),8);
    bufp->fullIData(oldp+54,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S0_N0__DOT__a_mantissa),24);
    bufp->fullBit(oldp+55,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S0_N0__DOT__b_sign));
    bufp->fullCData(oldp+56,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S0_N0__DOT__b_exponent),8);
    bufp->fullIData(oldp+57,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S0_N0__DOT__b_mantissa),24);
    bufp->fullBit(oldp+58,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S0_N0__DOT__o_sign));
    bufp->fullCData(oldp+59,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S0_N0__DOT__o_exponent),8);
    bufp->fullIData(oldp+60,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S0_N0__DOT__o_mantissa),25);
    bufp->fullCData(oldp+61,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S0_N0__DOT__diff),8);
    bufp->fullIData(oldp+62,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S0_N0__DOT__tmp_mantissa),24);
    bufp->fullCData(oldp+63,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S0_N0__DOT__i_e),8);
    bufp->fullIData(oldp+64,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S0_N0__DOT__i_m),25);
    bufp->fullCData(oldp+65,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S0_N0__DOT__o_e),8);
    bufp->fullIData(oldp+66,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S0_N0__DOT__o_m),25);
    bufp->fullBit(oldp+67,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S1_DN0__DOT__a_sign));
    bufp->fullBit(oldp+68,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S1_DN0__DOT__b_sign));
    bufp->fullBit(oldp+69,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S1_DN0__DOT__o_sign));
    bufp->fullIData(oldp+70,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT____Vcellinp__S1_2minDN0__b),32);
    bufp->fullCData(oldp+71,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S1_DN0__DOT__a_exponent),8);
    bufp->fullIData(oldp+72,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S1_DN0__DOT__a_mantissa),24);
    bufp->fullCData(oldp+73,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S1_DN0__DOT__b_exponent),8);
    bufp->fullIData(oldp+74,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S1_DN0__DOT__b_mantissa),24);
    bufp->fullCData(oldp+75,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S1_DN0__DOT__o_exponent),8);
    bufp->fullIData(oldp+76,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S1_DN0__DOT__o_mantissa),25);
    bufp->fullQData(oldp+77,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S1_DN0__DOT__product),48);
    bufp->fullCData(oldp+79,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S1_DN0__DOT__i_e),8);
    bufp->fullQData(oldp+80,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S1_DN0__DOT__i_m),48);
    bufp->fullCData(oldp+82,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S1_DN0__DOT__o_e),8);
    bufp->fullQData(oldp+83,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S1_DN0__DOT__o_m),48);
    bufp->fullIData(oldp+85,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S1_2min_DN0_out),32);
    bufp->fullBit(oldp+86,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S1_2minDN0__DOT__a_sign));
    bufp->fullCData(oldp+87,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S1_2minDN0__DOT__a_exponent),8);
    bufp->fullIData(oldp+88,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S1_2minDN0__DOT__a_mantissa),24);
    bufp->fullBit(oldp+89,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S1_2minDN0__DOT__b_sign));
    bufp->fullCData(oldp+90,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S1_2minDN0__DOT__b_exponent),8);
    bufp->fullIData(oldp+91,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S1_2minDN0__DOT__b_mantissa),24);
    bufp->fullBit(oldp+92,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S1_2minDN0__DOT__o_sign));
    bufp->fullCData(oldp+93,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S1_2minDN0__DOT__o_exponent),8);
    bufp->fullIData(oldp+94,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S1_2minDN0__DOT__o_mantissa),25);
    bufp->fullCData(oldp+95,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S1_2minDN0__DOT__diff),8);
    bufp->fullIData(oldp+96,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S1_2minDN0__DOT__tmp_mantissa),24);
    bufp->fullCData(oldp+97,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S1_2minDN0__DOT__i_e),8);
    bufp->fullIData(oldp+98,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S1_2minDN0__DOT__i_m),25);
    bufp->fullCData(oldp+99,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S1_2minDN0__DOT__o_e),8);
    bufp->fullIData(oldp+100,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S1_2minDN0__DOT__o_m),25);
    bufp->fullBit(oldp+101,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S1_N1__DOT__a_sign));
    bufp->fullBit(oldp+102,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S1_N1__DOT__b_sign));
    bufp->fullBit(oldp+103,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S1_N1__DOT__o_sign));
    bufp->fullIData(oldp+104,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__N1),32);
    bufp->fullCData(oldp+105,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S1_N1__DOT__a_exponent),8);
    bufp->fullIData(oldp+106,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S1_N1__DOT__a_mantissa),24);
    bufp->fullCData(oldp+107,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S1_N1__DOT__b_exponent),8);
    bufp->fullIData(oldp+108,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S1_N1__DOT__b_mantissa),24);
    bufp->fullCData(oldp+109,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S1_N1__DOT__o_exponent),8);
    bufp->fullIData(oldp+110,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S1_N1__DOT__o_mantissa),25);
    bufp->fullQData(oldp+111,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S1_N1__DOT__product),48);
    bufp->fullCData(oldp+113,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S1_N1__DOT__i_e),8);
    bufp->fullQData(oldp+114,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S1_N1__DOT__i_m),48);
    bufp->fullCData(oldp+116,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S1_N1__DOT__o_e),8);
    bufp->fullQData(oldp+117,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S1_N1__DOT__o_m),48);
    bufp->fullBit(oldp+119,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S2_DN1__DOT__a_sign));
    bufp->fullBit(oldp+120,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S2_DN1__DOT__b_sign));
    bufp->fullBit(oldp+121,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S2_DN1__DOT__o_sign));
    bufp->fullIData(oldp+122,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT____Vcellinp__S2_2minDN1__b),32);
    bufp->fullCData(oldp+123,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S2_DN1__DOT__a_exponent),8);
    bufp->fullIData(oldp+124,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S2_DN1__DOT__a_mantissa),24);
    bufp->fullCData(oldp+125,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S2_DN1__DOT__b_exponent),8);
    bufp->fullIData(oldp+126,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S2_DN1__DOT__b_mantissa),24);
    bufp->fullCData(oldp+127,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S2_DN1__DOT__o_exponent),8);
    bufp->fullIData(oldp+128,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S2_DN1__DOT__o_mantissa),25);
    bufp->fullQData(oldp+129,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S2_DN1__DOT__product),48);
    bufp->fullCData(oldp+131,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S2_DN1__DOT__i_e),8);
    bufp->fullQData(oldp+132,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S2_DN1__DOT__i_m),48);
    bufp->fullCData(oldp+134,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S2_DN1__DOT__o_e),8);
    bufp->fullQData(oldp+135,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S2_DN1__DOT__o_m),48);
    bufp->fullIData(oldp+137,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S2_2minDN1_out),32);
    bufp->fullBit(oldp+138,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S2_2minDN1__DOT__a_sign));
    bufp->fullCData(oldp+139,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S2_2minDN1__DOT__a_exponent),8);
    bufp->fullIData(oldp+140,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S2_2minDN1__DOT__a_mantissa),24);
    bufp->fullBit(oldp+141,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S2_2minDN1__DOT__b_sign));
    bufp->fullCData(oldp+142,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S2_2minDN1__DOT__b_exponent),8);
    bufp->fullIData(oldp+143,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S2_2minDN1__DOT__b_mantissa),24);
    bufp->fullBit(oldp+144,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S2_2minDN1__DOT__o_sign));
    bufp->fullCData(oldp+145,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S2_2minDN1__DOT__o_exponent),8);
    bufp->fullIData(oldp+146,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S2_2minDN1__DOT__o_mantissa),25);
    bufp->fullCData(oldp+147,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S2_2minDN1__DOT__diff),8);
    bufp->fullIData(oldp+148,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S2_2minDN1__DOT__tmp_mantissa),24);
    bufp->fullCData(oldp+149,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S2_2minDN1__DOT__i_e),8);
    bufp->fullIData(oldp+150,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S2_2minDN1__DOT__i_m),25);
    bufp->fullCData(oldp+151,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S2_2minDN1__DOT__o_e),8);
    bufp->fullIData(oldp+152,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S2_2minDN1__DOT__o_m),25);
    bufp->fullBit(oldp+153,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S2_N2__DOT__a_sign));
    bufp->fullBit(oldp+154,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S2_N2__DOT__b_sign));
    bufp->fullBit(oldp+155,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S2_N2__DOT__o_sign));
    bufp->fullIData(oldp+156,(vlSelf->top__DOT__dut__DOT__D1__DOT__b_reciprocal),32);
    bufp->fullBit(oldp+157,(vlSelf->top__DOT__dut__DOT__D1__DOT__mult__DOT__a_sign));
    bufp->fullBit(oldp+158,(vlSelf->top__DOT__dut__DOT__D1__DOT__mult__DOT__b_sign));
    bufp->fullBit(oldp+159,(vlSelf->top__DOT__dut__DOT__D1__DOT__mult__DOT__o_sign));
    bufp->fullCData(oldp+160,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S2_N2__DOT__a_exponent),8);
    bufp->fullIData(oldp+161,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S2_N2__DOT__a_mantissa),24);
    bufp->fullCData(oldp+162,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S2_N2__DOT__b_exponent),8);
    bufp->fullIData(oldp+163,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S2_N2__DOT__b_mantissa),24);
    bufp->fullCData(oldp+164,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S2_N2__DOT__o_exponent),8);
    bufp->fullIData(oldp+165,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S2_N2__DOT__o_mantissa),25);
    bufp->fullQData(oldp+166,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S2_N2__DOT__product),48);
    bufp->fullCData(oldp+168,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S2_N2__DOT__i_e),8);
    bufp->fullQData(oldp+169,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S2_N2__DOT__i_m),48);
    bufp->fullCData(oldp+171,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S2_N2__DOT__o_e),8);
    bufp->fullQData(oldp+172,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S2_N2__DOT__o_m),48);
    bufp->fullCData(oldp+174,(vlSelf->top__DOT__dut__DOT__D1__DOT__mult__DOT__a_exponent),8);
    bufp->fullIData(oldp+175,(vlSelf->top__DOT__dut__DOT__D1__DOT__mult__DOT__a_mantissa),24);
    bufp->fullCData(oldp+176,(vlSelf->top__DOT__dut__DOT__D1__DOT__mult__DOT__b_exponent),8);
    bufp->fullIData(oldp+177,(vlSelf->top__DOT__dut__DOT__D1__DOT__mult__DOT__b_mantissa),24);
    bufp->fullCData(oldp+178,(vlSelf->top__DOT__dut__DOT__D1__DOT__mult__DOT__o_exponent),8);
    bufp->fullIData(oldp+179,(vlSelf->top__DOT__dut__DOT__D1__DOT__mult__DOT__o_mantissa),25);
    bufp->fullQData(oldp+180,(vlSelf->top__DOT__dut__DOT__D1__DOT__mult__DOT__product),48);
    bufp->fullCData(oldp+182,(vlSelf->top__DOT__dut__DOT__D1__DOT__mult__DOT__i_e),8);
    bufp->fullQData(oldp+183,(vlSelf->top__DOT__dut__DOT__D1__DOT__mult__DOT__i_m),48);
    bufp->fullCData(oldp+185,(vlSelf->top__DOT__dut__DOT__D1__DOT__mult__DOT__o_e),8);
    bufp->fullQData(oldp+186,(vlSelf->top__DOT__dut__DOT__D1__DOT__mult__DOT__o_m),48);
    bufp->fullBit(oldp+188,(vlSelf->top__DOT__dut__DOT__o_sign));
    bufp->fullCData(oldp+189,(vlSelf->top__DOT__dut__DOT__o_exponent),8);
    bufp->fullIData(oldp+190,(vlSelf->top__DOT__dut__DOT__o_mantissa),25);
    bufp->fullIData(oldp+191,(vlSelf->top__DOT__dut__DOT__adder_a_in),32);
    bufp->fullIData(oldp+192,(vlSelf->top__DOT__dut__DOT__adder_b_in),32);
    bufp->fullBit(oldp+193,(vlSelf->clk_i));
    bufp->fullIData(oldp+194,(vlSelf->A),32);
    bufp->fullIData(oldp+195,(vlSelf->B),32);
    bufp->fullCData(oldp+196,(vlSelf->opcode),2);
    bufp->fullIData(oldp+197,(vlSelf->O),32);
    bufp->fullCData(oldp+198,((0xffU & (vlSelf->A >> 0x17U))),8);
    bufp->fullIData(oldp+199,(vlSelf->top__DOT__dut__DOT__a_mantissa),24);
    bufp->fullCData(oldp+200,((0xffU & (vlSelf->B >> 0x17U))),8);
    bufp->fullIData(oldp+201,(vlSelf->top__DOT__dut__DOT__b_mantissa),24);
    bufp->fullIData(oldp+202,((((IData)(vlSelf->top__DOT__dut__DOT__D1__DOT__mult__DOT__o_sign) 
                                << 0x1fU) | (((IData)(vlSelf->top__DOT__dut__DOT__D1__DOT__mult__DOT__o_exponent) 
                                              << 0x17U) 
                                             | (0x7fffffU 
                                                & vlSelf->top__DOT__dut__DOT__D1__DOT__mult__DOT__o_mantissa)))),32);
    bufp->fullBit(oldp+203,((vlSelf->A >> 0x1fU)));
    bufp->fullBit(oldp+204,((vlSelf->B >> 0x1fU)));
    bufp->fullIData(oldp+205,((((IData)(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S2_N2__DOT__o_sign) 
                                << 0x1fU) | (((IData)(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S2_N2__DOT__o_exponent) 
                                              << 0x17U) 
                                             | (0x7fffffU 
                                                & vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S2_N2__DOT__o_mantissa)))),32);
    bufp->fullIData(oldp+206,((((IData)(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S1_DN0__DOT__o_sign) 
                                << 0x1fU) | (((IData)(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S1_DN0__DOT__o_exponent) 
                                              << 0x17U) 
                                             | (0x7fffffU 
                                                & vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S1_DN0__DOT__o_mantissa)))),32);
    bufp->fullIData(oldp+207,((((IData)(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S2_DN1__DOT__o_sign) 
                                << 0x1fU) | (((IData)(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S2_DN1__DOT__o_exponent) 
                                              << 0x17U) 
                                             | (0x7fffffU 
                                                & vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S2_DN1__DOT__o_mantissa)))),32);
    bufp->fullIData(oldp+208,(vlSelf->top__DOT__dut__DOT__multiplier_a_in),32);
    bufp->fullIData(oldp+209,(vlSelf->top__DOT__dut__DOT__multiplier_b_in),32);
    bufp->fullIData(oldp+210,(vlSelf->top__DOT__dut__DOT__divider_a_in),32);
    bufp->fullIData(oldp+211,(vlSelf->top__DOT__dut__DOT__divider_b_in),32);
    bufp->fullBit(oldp+212,(0U));
    bufp->fullBit(oldp+213,(1U));
    bufp->fullCData(oldp+214,(vlSelf->top__DOT__dut__DOT__A1__DOT__tmp_exponent),8);
    bufp->fullIData(oldp+215,((0x40000000U | (0x7fffffU 
                                              & vlSelf->top__DOT__dut__DOT__divider_b_in))),32);
    bufp->fullIData(oldp+216,(0x4034b4b5U),32);
    bufp->fullIData(oldp+217,(0x3ff0f0f1U),32);
    bufp->fullIData(oldp+218,(0x40000000U),32);
    bufp->fullCData(oldp+219,(0x7fU),8);
    bufp->fullIData(oldp+220,(0xf0f0f1U),24);
    bufp->fullCData(oldp+221,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S0_N0__DOT__tmp_exponent),8);
    bufp->fullCData(oldp+222,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S1_2minDN0__DOT__tmp_exponent),8);
    bufp->fullCData(oldp+223,(vlSelf->top__DOT__dut__DOT__D1__DOT__recip__DOT__S2_2minDN1__DOT__tmp_exponent),8);
}
